// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcRrtoRl-EJ3TqrDdBA6LcP58mYyWI9VI',
    appId: '1:302627487998:web:a17fdc11905365d1ac25af',
    messagingSenderId: '302627487998',
    projectId: 'ngo-solution',
    authDomain: 'ngo-solution.firebaseapp.com',
    storageBucket: 'ngo-solution.firebasestorage.app',
    measurementId: 'G-RXBJE0T51H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApORkAro9N6pudcdp82W0I_Jq-79-rbQE',
    appId: '1:302627487998:android:9004c6325d698097ac25af',
    messagingSenderId: '302627487998',
    projectId: 'ngo-solution',
    storageBucket: 'ngo-solution.firebasestorage.app',
  );
}
